### ISSUE TITLE
Feature Request: Read Accounts & Roles from config file

### ISSUE THREAD

**Issue by qoomon** [coinbase/assume-role#10]
~/.aws/config
```
[profile iam]
 region = eu-central-1

[profile production]
source_profile = iam
role_arn = arn:aws:iam::1234567890:role/Administrator
region = eu-central-1
```

**Comment by grahamjenson** [comment]
This would be a good feature to have, though there is no roadmap for us including it, so I am leaving this issue open. 

Please feel free to submit a PR if you would like this feature sooner. Cheers.

**Comment by brainstorm** [comment]
@qoomon Not entirely what you suggest, but PR #21 might give you some hints on how to implement (and pullrequest) what you want? ;)

**Comment by qoomon** [comment]
@brainstorm I have created a click in Myanmar own already https://github.com/qoomon/aws-assume, thx anyway
