### ISSUE TITLE
FR: Output ACCOUNT_ROLE if called via 'eval'

### ISSUE THREAD

**Issue by jtheuer** [coinbase/assume-role#17]
Hi, great work on the tool! I try to write a wrapper for the fish-shell and it would be helpful if you can output the `ACCOUNT_ROLE` here so I can add it to the prompt:

https://github.com/coinbase/assume-role/blob/master/assume-role#L238-L249

```
  # OUTPUTS ALL THE EXPORTS for eval $(assume-role [args])
  if [ "$OUTPUT_TO_EVAL" = "true" ]; then
    echo "export AWS_REGION=\"$AWS_REGION\";"
    echo "export AWS_DEFAULT_REGION=\"$AWS_DEFAULT_REGION\";"
    echo "export AWS_ACCESS_KEY_ID=\"$AWS_ACCESS_KEY_ID\";"
    echo "export AWS_SECRET_ACCESS_KEY=\"$AWS_SECRET_ACCESS_KEY\";"
    echo "export AWS_SESSION_TOKEN=\"$AWS_SESSION_TOKEN\";"
    echo "export AWS_ACCOUNT_ID=\"$AWS_ACCOUNT_ID\";"
    echo "export AWS_ACCOUNT_NAME=\"$AWS_ACCOUNT_NAME\";"
    echo "export AWS_SESSION_ACCESS_KEY_ID=\"$AWS_SESSION_ACCESS_KEY_ID\";"
    echo "export AWS_SESSION_SECRET_ACCESS_KEY=\"$AWS_SESSION_SECRET_ACCESS_KEY\";"
    echo "export AWS_SESSION_SESSION_TOKEN=\"$AWS_SESSION_SESSION_TOKEN\";"
    echo "export AWS_SESSION_START=\"$AWS_SESSION_START\";"
    echo "export GEO_ENV=\"$GEO_ENV\";"
  fi
```

**Comment by grahamjenson** [comment]
Fixed in https://github.com/coinbase/assume-role/pull/15 will merge soonish

**Comment by grahamjenson** [comment]
A PR that outputs AWS_ACCOUNT_ROLE has been merged, but has b=not been updated to brew.

**Comment by grahamjenson** [comment]
Also, once you have finished writing a fish wrapper please link it to me, I would love to reference it in the readme as people have approached me to support other shells.

**Comment by jtheuer** [comment]
That was quick! Thanks a lot! I already have a fish function in place that let's me run it from fish:

```fish
function role
   read -n6 -P"MFA Token: " mfa_token
   set --erase AWS_ACCOUNT_ROLE   # can be removed after the PR is merged
   assume-role $argv $mfa_token | sed 's/^export/set -x --global/' | sed 's/=/ /' | source
   set -x --global AWS_ACCOUNT_ROLE "$argv[2]"  # can be removed after the PR is merged
end
```

It would be great of course if the `read` doesn't need to be done from fish, of course. If you have a good idea how to improve that, let me know. I think it only calls `read` if I call the script in a certain fashion, right?

Would you rather want to implement support for multiple shells in assume-role or provide a generic response that one wraps in their favourite shell's function?

**Comment by grahamjenson** [comment]
I think it would be difficult to implement assume-role for multiple shells without rewriting it from scratch. So for now I prefer wrapping it.

The `read` call is not made if the script is called with all the parameters.

**Comment by jtheuer** [comment]
Ok, just checked, when I remove the `$mfa_token` parameter then the script outputs `mfa_token is not defined`. Maybe calling it from fish shell runs into an unexpected [here](https://github.com/coinbase/assume-role/blob/master/assume-role#L266) ?

Having the `read` working cross-shell would probably be good, the multi-shell support might be too troublesome.

I also included yubikey MFA support in my function if you are interested as optional support? This is pretty cool since it reads the code directly from the stick using `ykman oath code -s "my-code-alias"`.

**Comment by grahamjenson** [comment]
If you want to add yubikey support to `assume-role` I would merge that PR 100% :) 

You could reimplement the read in your wrapper, to make sure you pass the correct envars. That would be easiest I think.

**Comment by jtheuer** [comment]
Cool, will try to find a good way to add it (will open a new issue to discuss details).
About the read: What do you mean by "pass envars"? Currently I pass the MFA code as argument.

It would probably be a good workflow to check the yubikey first and then fall back to user input. This would require however that either both, read and yubikey are in the wrapper script or both are in `assume-role`. What do you think?
