### ISSUE TITLE
aws cli expects AWS_DEFAULT_REGION

### ISSUE THREAD

**Issue by skehlet** [coinbase/assume-role#2]
Very useful tool, just discovered one small thing, it appears the [expected env var](http://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html) is `AWS_DEFAULT_REGION` instead of `AWS_REGION`.

p.s. also discovered a neat bonus feature, that if you're juggling multiple accounts (e.g. home, work) and want to use a profile besides `default`, you can invoke `assume-role` like:
```
AWS_PROFILE=your-non-default-profile assume-role your-account your-role your-code
```
Great stuff, thanks!

**Comment by grahamjenson** [comment]
Hey, thanks for pointing out the bug. I am currently, writing a PR to fix the issue, should have that out today.

Also great demonstration of another way to use the tool.

Cheers!

**Comment by chancez** [comment]
I also stumbled into this. It might be useful for it to print which profile it's using as it took me a bit to realize I had to set that for this. It might also be nice to be able to specify the profile to use as an arg/flag.
