### ISSUE TITLE
Improved fish support

### ISSUE THREAD

**Issue by jtheuer** [coinbase/assume-role#32]
Hi, I was able to improve the fish shell support, but wanted to check with you if that is an approach you would support before creating a PR:

Basically I took over your "init" stub and named it shell. It shall output an "eval"-able result:

```
elif [[ "shell" == "${1}" ]]; then
  # TODO: This will be multi-shell support like rbenv, e.g. fish
  # Supports "assume-role shell [account] [role]" | <translate syntax> | source in your favourite shell
  set -eo pipefail
  OUTPUT_TO_EVAL="true"
  shift
  assume-role "$@";
```

BUT to enable the interactive mfa prompt (which I really want to have with fish) I had to redirect the prompt to stderr:

```
    if [ -z "$mfa_token_input" ]; then            # removed: && [ -z "$OUTPUT_TO_EVAL" ]
      echo -n "MFA Token: " >> /dev/stderr  # redirected user prompts to stderr - should this be used everywhere to enable interactive prompts when caledl via eval or source pipe?
      read -r -s mfa_token
```

You can now have a function like this in fish:

```
function role2
   assume-role shell $argv | sed 's/^export/set -x --global/' | sed 's/=/ /' | source
end
```

Is that an approach worth to follow for you? Any suggestions for improvements?

Jan

**Comment by grahamjenson** [comment]
I like that. I know some people that use fish that would love more support for it.

I think that you are right and that `echo -n "MFA Token: " >> /dev/stderr` should probably be there. I am not sure about the consequences for people using `OUTPUT_TO_EVAL` as it might start prompting them.

What is the difference between calling with the `shell` first argument and calling it normally, the only difference I see is the `shift`.

I also love the idea creating a function that wraps the piping to source, might steal that trick.

Please submit a PR we can work on it from there.
