### ISSUE TITLE
Support for YubiKey as multi-factor authentication

### ISSUE THREAD

**Issue by eredi93** [coinbase/assume-role#34]
Now is possible to use a YubiKey as MFA device
https://aws.amazon.com/blogs/security/use-yubikey-security-key-sign-into-aws-management-console/

assume-role works with OTP only. do you have any plans to support YubiKeys?

**Comment by jtheuer** [comment]
@eredi93 did you find any information if yubikeys as u2f device are supported on the command-line as well? Is that even possible?

I was thinking about adding a PR for  yubikey oath support via `ykman` though...

**Comment by eredi93** [comment]
After contacting AWS support i discovered this 😭 :

> AWS currently supports using U2F security keys only in the AWS Management Console. Using U2F security keys for MFA is not currently supported in the AWS CLI and AWS API, or for access to MFA-protected API operations.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_mfa_u2f_supported_configurations.html

this is sad, but i guess we should close this as there isn't much we can do 😢

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
