### ISSUE TITLE
Share STS session between different shells

### ISSUE THREAD

**Issue by philsnow** [coinbase/assume-role#44]
I use screen heavily, and it's a pain to either have to enter an MFA token into any shell window I want to run a command from or run all my commands from just one shell.

`assume-role` already has an extra file in `~/.aws` (`accounts`).  What would you think of persisting what's currently kept in the `AWS_SESSION_*` environment variables in a new file `~/.aws/session`?  `assume-role-with-bastion` would read that file at the beginning and rewrite it on success.  This way, no matter what shell you run `assume-role prod rolename` from, it will use the same STS token.

**Comment by grahamjenson** [comment]
I feel your pain, but I think the session-file feature should not be in assume-role. If I am using lots of `assume-role`ing around, I will typically assume-role, then spin up a tmux session using a script like:

```
#!/bin/bash
tmux kill-session -t "accounts"

set -e

tmux -2 new-session -d -s "accounts"

for account in staging production <the rest>; do
  tmux new-window -n $account
  tmux select-window -t $account
  tmux send-keys "echo $account" C-m

  tmux send-keys "assume-role $account sudo" C-m
  tmux send-keys "$1" C-m
done

tmux a
```

This will spin up and assume into all the accounts I typically use and execute a command. 

Maybe your solution of a temporary file could be a wrapping script of assume-role. If you do create such a script, please share :)

**Comment by philsnow** [comment]
That's fair.

Another criticism of my suggestion that I thought of after filing this issue was:  currently the (presumably privileged) assumed role's credentials are kept only in environment variables, so it's not enough for an attacker to be able to walk the filesystem to get the assumed role's creds.  My suggestion puts those creds in the filesystem.

One thing I don't like about your approach is that I have to remember to do it beforehand, _but_ screen lets you stuff commands into the surrounding (or any other) screen session, so I can do something like

``` shell
$ assume-role envname rolename 123456
$ screen -X setenv AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
$ screen -X setenv AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
$ screen -X setenv AWS_SESSION_TOKEN $AWS_SESSION_TOKEN
```

and then any other screen windows I open will have the assumed role's credentials.  I have a two-level screen nesting setup, so if I wanted all my new screen sessions inside my "meta" screen session to have the vars, I just have to write

``` shell
$ screen -S meta -X setenv AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
...
```

I'd be really surprised if tmux doesn't have that ability but I don't know the incantation off the top of my head.
