### ISSUE TITLE
`source $(which assume-role)` broken

### ISSUE THREAD

**Issue by estraph** [coinbase/assume-role#54]
Since https://github.com/coinbase/assume-role/pull/53 we can no longer `source $(which assume-role)` in `.zshrc`, it fails with `exit 1`:

```
➜  ~ source $(which assume-role)
 assume-role is a command line tool to help assume roles through a bastion account with MFA.
 Store your bastion account credentials here ~/.aws/credentials

 Usage: assume-role [account_name] [role] [mfa_token] [aws-region]

 account_name          account id or alias
                       aliases stored in ~/.aws/accounts as JSON {"alias": account_id}
                       [default 'default']
 role                  the role to assume into the account
                       [default 'read']
 mfa_token             The MFA token for the user
                       only valid if not using SAML for auth

 aws_region            region to assume into default set in ~/.aws/config
Error: exit status 1
exit status 1
```

I think it's because of how this gets evaluated without args on `source`:

https://github.com/coinbase/assume-role/blob/860f89502f2a7f012422db683527c89e4e5d41f0/assume-role#L41-L44

The documentation states that this should be possible, and we've been able to do this successfully until this recent change.

https://github.com/coinbase/assume-role/blob/860f89502f2a7f012422db683527c89e4e5d41f0/README.md#L52

**Comment by estraph** [comment]
Workaround for anyone hitting this after a fresh install.

```zsh
# download the previously working version of assume-role
sudo curl -L https://raw.githubusercontent.com/coinbase/assume-role/5e3290a6f6cf4ab33734b90b487354b6d44c1aab/assume-role --output /usr/local/bin/assume-role

# make it executable
sudo chmod +x /usr/local/bin/assume-role
```

**Comment by estraph** [comment]
@itstehkman anyone installing assume-role as per [docs](https://github.com/coinbase/assume-role#via-bash-linuxmacos) using the provided [install-assume-role](https://github.com/coinbase/assume-role/blob/master/install-assume-role) script will get a broken version, because it pulls the latest version from master.

https://github.com/coinbase/assume-role/blob/860f89502f2a7f012422db683527c89e4e5d41f0/README.md#L35-L37

https://github.com/coinbase/assume-role/blob/860f89502f2a7f012422db683527c89e4e5d41f0/install-assume-role#L43

**Comment by estraph** [comment]
Hi folks - any plans to revert the bad PR to unbreak master and the installer?

**Comment by virgilwashere** [comment]
You just move the "**no args**" check to the bottom `if` block, to right after `set -eo pipefail`..

https://github.com/coinbase/assume-role/blob/860f89502f2a7f012422db683527c89e4e5d41f0/assume-role#L40-L44

Having said that, if you re-read the [referenced StackOverflow post](https://stackoverflow.com/a/28776166/11021293), this stands out:

`(return 0 2>/dev/null) && __sourced__=1 || __sourced__=0`

May I suggest this:

```bash
# END USAGE DOCUMENTATION

# do nothing in case the library is sourced more than once in the same shell
((${__sourced__-})) && return
(return 0 2>/dev/null) && __sourced__=1 || __sourced__=0

usage() {
```

Then you can change "**no args**" to:

```bash
if [ $# -eq 0 ] && [ ${__sourced__-} -eq 0 ]; then
  usage;
  return 2 2>/dev/null || exit 2
fi
```

And finish up with this at the end:

```bash
# from https://stackoverflow.com/questions/2683279/how-to-detect-if-a-script-is-being-sourced
if ((${__sourced__-})); then
  # Supports `source $( command -v assume_role)` in rc file for bash and zsh
  : # noop 
  printf 'I am sauced bro, sauced as\n' >&2
...
```

🍻 🍻 🍻 

I hope this is not out of line...

...and back to hacking on (my first!!!) python AWS SAML script.

Virgil

**Comment by estraph** [comment]
This is still broken, are there no plans to fix this? At the very least reverting the problematic PR would unblock users. I'm skeptical of the value of improved help output at the cost of breaking core functionality.

**Comment by jtheuer** [comment]
I can confirm that this is broken, thanks for providing a quickfix (installing an older version!)

**Comment by tanasegabriel** [comment]
@grahamjenson are there any plans to address this?

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
