### ISSUE TITLE
assume-role failing due to python errors

### ISSUE THREAD

**Issue by LohithBlaze** [coinbase/assume-role#55]
Hi,

recently I had installed anaconda but due to disk space issues, I had to delete the whole anaconda stack and tried using the default python, but assume-role always fails with the following error.

$ assume-role dev admin
Using assume-role default profile: securezapp-root
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000011954d5c0 (most recent call first):
MFA Token: ******

Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000000010e9955c0 (most recent call first):
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x0000000112d165c0 (most recent call first):
aws iam list-mfa-devices error

I have tried the following things,
https://stackoverflow.com/questions/5694706/py-initialize-fails-unable-to-load-the-file-system-codec/45423949#45423949

brew install python3
cd /usr/local/bin
rm python3
ln -s /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/‌​Versions/3.7/bin/pyt‌​hon3.7 /usr/local/bin/python3

I dont know how to resolve this problem and I have been working on this for a day now, any help would be greatly appreciated.

**Comment by grahamjenson** [comment]
This looks like an issue with aws-cli. Given assume-role doesn't call out to python other than through `aws`. I would try testing and possibly posting there, as I am not sure what your issue could be.
