### ISSUE TITLE
How to specify external ID in sts assume-role call?

### ISSUE THREAD

**Issue by jhecking** [coinbase/assume-role#56]
When assuming a cross-account role in a customer’s account, I need to specify an external ID that’s associated with that customer. [1] It seems currently the assume-role function always uses the account ID of the target account as the external ID:

https://github.com/coinbase/assume-role/blob/860f89502f2a7f012422db683527c89e4e5d41f0/assume-role#L356

I’m not sure what would be the best way to specify the external ID:
* Adding another positional command parameter to the function seems doable but not very usable. I’d really just like to specify the target account name and lookup the associated external ID automatically.
* The ~/.aws/accounts seems the obvious place to store this mapping, but the existing format of the file doesn’t lend itself to such an extension easily. Maybe the account name could map to an object with accountId and externalId (optional) keys?
* Or we could add a new file to store this mapping, e.g. ~/.aws/externalIds.

Any other suggestions? I’d be happy to help with the implementation and provide a PR, if I could get some guidance on which approach would likely be accepted.

[1] How to Use an External ID When Granting Access to Your AWS Resources to a Third Party: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
