### ISSUE TITLE
Invalid length for parameter SAMLAssertion, value: 0, valid range: 4-inf

### ISSUE THREAD

**Issue by wes-novack** [coinbase/assume-role#57]
Hello and thank you for the excellent assume-role tool. I have it working when using an IAM user in a bastion account, but I am now attempting to convert my usage over to a SAML integration with Okta, and running into issues.

I have the following env vars set (among others) in my .bashrc file.
```
export AWS_ASSUME_ROLE_AUTH_SCHEME='saml' # defaults to bastion
export SAML_IDP_ASSERTION_URL="https://redacted.okta.com/app/amazon_aws/redactedhash/sso/saml"
export SAML_IDP_NAME="name-of-my-idp-in-aws"
export SAML_IDP_REQUEST_BODY_TEMPLATE='{"service": "aws", "email": "$saml_user", "password": "$saml_password"}'
```
I used a URL found in my AWS identity provider metadata to populate that SAML_IDP_ASSERTION_URL

However, when I attempt to authenticate using the CLI, I get the following errors:
```
Gathering SAML credentials...
Password: 
Authenticating with SAML provider...
parse error: Invalid numeric literal at line 1, column 10

Parameter validation failed:
Invalid length for parameter SAMLAssertion, value: 0, valid range: 4-inf
```

Any suggestions?

**Comment by wes-novack** [comment]
I think I don't have the correct `SAML_IDP_ASSERTION_URL` configured, but how do I find the correct value for that?

**Comment by itstehkman** [comment]
Hey @wes-novack, glad to hear you liked the tool! So the weird thing is that SAML is a browser based protocol (it depends on HTTP redirects), so what we did is exposed an api endpoint that we created internally that would return a SAML response.

That way, you could get the SAML response without having to follow redirects from the CLI. Hope that helps!

**Comment by wes-novack** [comment]
@itstehkman appreciate the info! I'll continue testing and experimenting. I was also pointed to an Okta SAML debug tool (browser extension) that I'm going to try out.

**Comment by itstehkman** [comment]
sweet - also this resource is incredible for debuggin SAML: https://www.samltool.com/online_tools.php

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
