### ISSUE TITLE
account_id "xxxxxxxxxxx" is incorrectly formatted AWS account id

### ISSUE THREAD

**Issue by trnubo** [coinbase/assume-role#7]
When using the `~/.aws/accounts` file AWS account ids that start with a 0 (zero) throw the error `account_id "xxxxxxxxxxx" is incorrectly formatted AWS account id`

It seems that because the id is specified as a json number the leading zero is removed. Then if the id is specified as a string the following error is thrown.

`account_id ""xxxxxxxxxxxx"" is incorrectly formatted AWS account id`

I think the solution is to use jq `--raw-output` on the account_id look up. However there may have been a good reason to use a number for the account id, I've only just started using this.

**Comment by grahamjenson** [comment]
excellent issue, I have not run into. I will test this out and try get a fix for it out.

**Comment by grahamjenson** [comment]
I have added a fix and released a new version. To have accounts that start with 0 you need to use a string in the accounts file.

**Comment by indistinctTalk** [comment]
I just ran into this issue and wasted some time playing around before finding this issue - ideally this would be demonstrated in the README.md. I don't mind creating a pull request if you don't have time.
